{% set name = "supabase" %}
{% set version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ef00299c2de139ba4faee7c9fef626af4901f93dec0678bd8530d26051d8a6f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - postgrest >=0.14,<0.17.0
    - realtime >=2.0.0,<3.0.0
    - gotrue >=1.3,<3.0
    - httpx >=0.24,<0.28
    - storage3 >=0.5.3,<0.8.0
    - supafunc >=0.3.1,<0.6.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - supabase

about:
  home: https://github.com/supabase-community/supabase-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client for Supabase
  description: |
    Python Client for Supabase

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
