{% set name = "supabase" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b21b610c7a53e16964c2ce443e62ac2209045561c4fc3120b1627cfe186b76c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - typing-extensions >=4.12.2,<5.0.0
    - python >=3.8.0,<4.0.0
    - postgrest >=0.14,<0.18.0
    - realtime >=2.0.0,<3.0.0
    - gotrue >=1.3,<3.0
    - httpx >=0.24,<0.28
    - storage3 >=0.5.3,<0.9.0
    - supafunc >=0.3.1,<0.7.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - supabase

about:
  home: https://github.com/supabase/supabase-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client for Supabase
  description: |
    Python Client for Supabase

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
