{% set name = "supabase" %}
{% set version = "2.22.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9a163b73a97f737b5b16496ccd4735c2d1fd7ed1bea390a86490f6b3b416c21

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
    - uv-build
  run:
    - supabase-auth
    - supabase-functions
    - typing_extensions >=4.12.2,<5.0.0
    - typing-extensions >=4.12.2,<5.0.0
    - python >={{ python_min }},<4.0.0
    - postgrest
    - realtime
    - gotrue >=2.11.0,<3.0.0
    - httpx >=0.26,<0.29
    - storage3
    - supafunc >=0.9,<0.11

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - supabase

about:
  home: https://github.com/supabase/supabase-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client for Supabase
  description: |
    Python Client for Supabase

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
