{% set name = "supabase" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89b6556bf4f5f2e3dd1255f5840ceb12c3dc187ce8947b9bc0f5f7b0ad010971

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - postgrest >=0.10.8,<0.14.0
    - realtime >=1.0.0,<2.0.0
    - gotrue >=1.3.0,<2.0.0
    - httpx >=0.24.0,<0.25.0
    - storage3 >=0.5.3,<0.7.0
    - supafunc >=0.3.1,<0.4.0

test:
  imports:
    - supabase

about:
  home: https://github.com/supabase-community/supabase-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client for Supabase
  description: |
    Python Client for Supabase

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
