{% set name = "supabase" %}
{% set version = "2.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 205787b1fbb43d6bc997c06fe3a56137336d885a1b56ec10f0012f2a2905285d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - supabase-auth ==2.12.3
    - supabase-functions ==0.10.1
    - typing_extensions >=4.12.2,<5.0.0
    - typing-extensions >=4.12.2,<5.0.0
    - python >={{ python_min }},<4.0.0
    - postgrest ==1.1.1
    - realtime ==2.7.0
    - gotrue >=2.11.0,<3.0.0
    - httpx >=0.26,<0.29
    - storage3 ==0.12.1
    - supafunc >=0.9,<0.11

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - supabase

about:
  home: https://github.com/supabase/supabase-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client for Supabase
  description: |
    Python Client for Supabase

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
