{% set name = "supabase" %}
{% set version = "2.27.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e5a348232ac4315c1032ddd687278f0b982465471f0cbb52bca7e6a66495ff3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
    - uv-build
  run:
    - yarl >=1.22.0
    - supabase-auth ==2.27.3
    - supabase-functions ==2.27.3
    - typing_extensions >=4.12.2,<5.0.0
    - typing-extensions >=4.12.2,<5.0.0
    - python >={{ python_min }},<4.0.0
    - postgrest ==2.27.3
    - realtime ==2.27.3
    - gotrue >=2.11.0,<3.0.0
    - httpx >=0.26,<0.29
    - storage3 ==2.27.3
    - supafunc >=0.9,<0.11

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - supabase

about:
  home: https://github.com/supabase/supabase-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client for Supabase
  description: |
    Python Client for Supabase

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
