{% set name = "supabase" %}
{% set version = "2.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98f3810158012d4ec0e3083f2e5515f5e10b32bd71e7d458662140e963c1d164

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - typing_extensions >=4.12.2,<5.0.0
    - typing-extensions >=4.12.2,<5.0.0
    - python >={{ python_min }},<4.0.0
    - postgrest >0.19,<1.2
    - realtime >=2.4.0,<2.6.0
    - gotrue >=2.11.0,<3.0.0
    - httpx >=0.26,<0.29
    - storage3 >=0.10,<0.13
    - supafunc >=0.9,<0.11

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - supabase

about:
  home: https://github.com/supabase/supabase-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client for Supabase
  description: |
    Python Client for Supabase

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
